[versions]
kotlin = "2.3.21"
agp = "8.13.2"
jna = "5.18.1"
androidx-annotation = "1.7.1"

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "androidx-annotation" }
